# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: miner.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='miner.proto',
  package='bc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bminer.proto\x12\x02\x62\x63\x1a\ncore.proto\"[\n\x10\x42lockFingerprint\x12\x12\n\nblockchain\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x12\n\nis_current\x18\x04 \x01(\x08\"\xf0\x01\n\x0cMinerRequest\x12\x0f\n\x07work_id\x18\x01 \x01(\t\x12\x19\n\x11\x63urrent_timestamp\x18\x02 \x01(\x04\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\x0c\n\x04work\x18\x04 \x01(\t\x12\x11\n\tminer_key\x18\x05 \x01(\t\x12\x13\n\x0bmerkle_root\x18\x06 \x01(\t\x12\x12\n\ndifficulty\x18\x07 \x01(\t\x12(\n\x13last_previous_block\x18\x08 \x01(\x0b\x32\x0b.bc.BcBlock\x12\x30\n\x11new_block_headers\x18\t \x01(\x0b\x32\x15.bc.BlockchainHeaders\"\xa7\x01\n\rMinerResponse\x12\'\n\x06result\x18\x01 \x01(\x0e\x32\x17.bc.MinerResponseResult\x12\r\n\x05nonce\x18\x02 \x01(\t\x12\x12\n\ndifficulty\x18\x03 \x01(\t\x12\x10\n\x08\x64istance\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x12\n\niterations\x18\x06 \x01(\x04\x12\x11\n\ttime_diff\x18\x07 \x01(\x04*6\n\x13MinerResponseResult\x12\x0c\n\x08\x43\x61nceled\x10\x00\x12\x06\n\x02Ok\x10\x01\x12\t\n\x05\x45rror\x10\x02\x32\x36\n\x05Miner\x12-\n\x04Mine\x12\x10.bc.MinerRequest\x1a\x11.bc.MinerResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[core__pb2.DESCRIPTOR,])

_MINERRESPONSERESULT = _descriptor.EnumDescriptor(
  name='MinerResponseResult',
  full_name='bc.MinerResponseResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Canceled', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ok', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=537,
  serialized_end=591,
)
_sym_db.RegisterEnumDescriptor(_MINERRESPONSERESULT)

MinerResponseResult = enum_type_wrapper.EnumTypeWrapper(_MINERRESPONSERESULT)
Canceled = 0
Ok = 1
Error = 2



_BLOCKFINGERPRINT = _descriptor.Descriptor(
  name='BlockFingerprint',
  full_name='bc.BlockFingerprint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockchain', full_name='bc.BlockFingerprint.blockchain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='bc.BlockFingerprint.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bc.BlockFingerprint.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_current', full_name='bc.BlockFingerprint.is_current', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=122,
)


_MINERREQUEST = _descriptor.Descriptor(
  name='MinerRequest',
  full_name='bc.MinerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='work_id', full_name='bc.MinerRequest.work_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_timestamp', full_name='bc.MinerRequest.current_timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='bc.MinerRequest.offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='work', full_name='bc.MinerRequest.work', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='miner_key', full_name='bc.MinerRequest.miner_key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle_root', full_name='bc.MinerRequest.merkle_root', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='bc.MinerRequest.difficulty', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_previous_block', full_name='bc.MinerRequest.last_previous_block', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_block_headers', full_name='bc.MinerRequest.new_block_headers', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=365,
)


_MINERRESPONSE = _descriptor.Descriptor(
  name='MinerResponse',
  full_name='bc.MinerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='bc.MinerResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='bc.MinerResponse.nonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='bc.MinerResponse.difficulty', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='bc.MinerResponse.distance', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bc.MinerResponse.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iterations', full_name='bc.MinerResponse.iterations', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_diff', full_name='bc.MinerResponse.time_diff', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=535,
)

_MINERREQUEST.fields_by_name['last_previous_block'].message_type = core__pb2._BCBLOCK
_MINERREQUEST.fields_by_name['new_block_headers'].message_type = core__pb2._BLOCKCHAINHEADERS
_MINERRESPONSE.fields_by_name['result'].enum_type = _MINERRESPONSERESULT
DESCRIPTOR.message_types_by_name['BlockFingerprint'] = _BLOCKFINGERPRINT
DESCRIPTOR.message_types_by_name['MinerRequest'] = _MINERREQUEST
DESCRIPTOR.message_types_by_name['MinerResponse'] = _MINERRESPONSE
DESCRIPTOR.enum_types_by_name['MinerResponseResult'] = _MINERRESPONSERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockFingerprint = _reflection.GeneratedProtocolMessageType('BlockFingerprint', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKFINGERPRINT,
  '__module__' : 'miner_pb2'
  # @@protoc_insertion_point(class_scope:bc.BlockFingerprint)
  })
_sym_db.RegisterMessage(BlockFingerprint)

MinerRequest = _reflection.GeneratedProtocolMessageType('MinerRequest', (_message.Message,), {
  'DESCRIPTOR' : _MINERREQUEST,
  '__module__' : 'miner_pb2'
  # @@protoc_insertion_point(class_scope:bc.MinerRequest)
  })
_sym_db.RegisterMessage(MinerRequest)

MinerResponse = _reflection.GeneratedProtocolMessageType('MinerResponse', (_message.Message,), {
  'DESCRIPTOR' : _MINERRESPONSE,
  '__module__' : 'miner_pb2'
  # @@protoc_insertion_point(class_scope:bc.MinerResponse)
  })
_sym_db.RegisterMessage(MinerResponse)



_MINER = _descriptor.ServiceDescriptor(
  name='Miner',
  full_name='bc.Miner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=593,
  serialized_end=647,
  methods=[
  _descriptor.MethodDescriptor(
    name='Mine',
    full_name='bc.Miner.Mine',
    index=0,
    containing_service=None,
    input_type=_MINERREQUEST,
    output_type=_MINERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MINER)

DESCRIPTOR.services_by_name['Miner'] = _MINER

# @@protoc_insertion_point(module_scope)
