#!/usr/bin/env python3
import argparse 
import apiglue

parser = argparse.ArgumentParser(description='Map miner grpc to unform json rpc interface.')
parser.add_argument("--bind", type=str, default="localhost", help="IP to bind server to.")
parser.add_argument("--grpc_port", type=int, default=50052, help="Port to listen for incoming grpc mining requests.")
parser.add_argument("--api_port", type=int, default=3001, help="Port to listen for incoming json api requests.")
parser.add_argument("--test", action="store_true", default=False, help="Run basic sanity checks.")

args = parser.parse_args()

if args.bind is None:
    raise Exception('Must specify IP to bind to with --bind!')

bridge = apiglue.grpc_reformatter(args.bind,
                                  bc_port=args.grpc_port,
                                  api_port=args.api_port)

bridge.start_server()

if args.test:
    bridge.test()

bridge.wait_on_server()
